name: "assigned issues are in progress"
on:
  issues:
    types: [assigned]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project-url: "https://github.com/notanimposter/3den/projects/3"
        column-name: "In progress"
