on:
  issues:
    types: [unlabeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project-url: "https://github.com/notanimposter/3den/projects/3"
        column-name: "Triage"
        label-name: "blocked"
        columns-to-ignore: "Review,Done"
